//! Pass F: usable in-world terminals.
//!
//! Every placed computer/monitor prop whose `{kit}/{stem}` appears in
//! `assets/models/screen_catalog.json` (generated by
//! `tools/probe_screen_quads.py`) gets an emissive screen quad glued onto the
//! probed screen rectangle. Walk up to one and a "[E] terminal" prompt shows;
//! E focuses the camera on the screen, sets `netplay::InputCapture` (movement,
//! guns, Tab all freeze — same contract as the NPC dialogue) and routes the
//! keyboard into a fake unix shell ([`crate::terminal_shell::Shell`]). The
//! shell is drawn with a `Text2d` + offscreen `Camera2d` into the live screen
//! texture, so the session literally plays out on the in-world monitor. Esc
//! disconnects. Client-only flavor for now — no server round-trips.

use bevy::asset::RenderAssetUsages;
use bevy::camera::visibility::RenderLayers;
use bevy::camera::{ImageRenderTarget, RenderTarget};
use bevy::input::keyboard::{Key, KeyboardInput};
use bevy::input::ButtonState;
use bevy::light::NotShadowCaster;
use bevy::prelude::*;
use bevy::render::render_resource::{
    Extent3d, TextureDimension, TextureFormat, TextureUsages,
};
use bevy::sprite::Anchor;
use bevy::transform::TransformSystems;
use std::collections::HashMap;

use crate::fly_camera::FlyCamera;
use crate::netplay::{InputCapture, OwnPlayer};
use crate::terminal_shell::Shell;
use crate::test_showcase::KenneyModule;
use crate::ui_theme as theme;
use shared::protocol::{Npc, PlayerAlive};

/// "[E] terminal" shows within this range when looking at a screen.
const PROMPT_RANGE: f32 = 2.8;
/// Walking (being shoved) past this distance disconnects the session.
const CLOSE_RANGE: f32 = 3.5;
/// How much the camera-forward must agree with the direction to the screen.
const FACING_DOT: f32 = 0.88;
/// Live render target — 16:10, comfortably readable at fullscreen focus.
const LIVE_W: u32 = 512;
const LIVE_H: u32 = 320;
/// Shell grid that fits the live target at font_size 15 (Fira Mono default).
const SHELL_COLS: usize = 54;
const SHELL_ROWS: usize = 17;
/// Everything terminal-related renders on this offscreen layer.
const TERMINAL_LAYER: usize = 3;

pub struct TerminalPlugin;

impl Plugin for TerminalPlugin {
    fn build(&self, app: &mut App) {
        app.insert_resource(load_screen_catalog())
            .init_resource::<TerminalFocus>()
            .add_systems(Startup, (setup_terminal_assets, spawn_prompt))
            .add_systems(
                Update,
                (
                    attach_screens,
                    // Before send_input: an E that opens a terminal must not
                    // also travel to the server as an NPC interact.
                    prompt_and_open.before(crate::netplay::send_input),
                    terminal_keys,
                    auto_close,
                ),
            )
            // Right after Bevy records this frame's keyboard: while a session
            // is open, every key except Esc belongs to the in-game computer.
            .add_systems(
                PreUpdate,
                block_keys_during_session.after(bevy::input::InputSystems),
            )
            // After every Update camera driver (first/third person, playtest
            // orbit, wall avoidance): the focus blend gets the last word on
            // the camera transform before it propagates.
            .add_systems(
                PostUpdate,
                focus_camera.before(TransformSystems::Propagate),
            );
    }
}

// --- screen catalog ----------------------------------------------------------

#[derive(Clone, Copy)]
struct QuadSpec {
    center: Vec3,
    normal: Vec3,
    up: Vec3,
    size: Vec2,
}

/// `{kit}/{stem}` → screen quads in GLB-local units (scaled by the piece).
#[derive(Resource)]
struct ScreenCatalog(HashMap<String, Vec<QuadSpec>>);

fn load_screen_catalog() -> ScreenCatalog {
    let raw: serde_json::Value =
        serde_json::from_str(include_str!("../../../assets/models/screen_catalog.json"))
            .expect("screen_catalog.json must be valid JSON");
    let mut map = HashMap::new();
    let Some(obj) = raw.as_object() else {
        return ScreenCatalog(map);
    };
    let vec3 = |v: &serde_json::Value| {
        let a = v.as_array()?;
        Some(Vec3::new(
            a.first()?.as_f64()? as f32,
            a.get(1)?.as_f64()? as f32,
            a.get(2)?.as_f64()? as f32,
        ))
    };
    for (key, entry) in obj {
        let Some(quads) = entry.get("quads").and_then(|q| q.as_array()) else {
            continue;
        };
        let parsed: Vec<QuadSpec> = quads
            .iter()
            .filter_map(|q| {
                let size = q.get("size_wh")?.as_array()?;
                Some(QuadSpec {
                    center: vec3(q.get("center")?)?,
                    normal: vec3(q.get("normal")?)?.normalize(),
                    up: vec3(q.get("up")?)?.normalize(),
                    size: Vec2::new(
                        size.first()?.as_f64()? as f32,
                        size.get(1)?.as_f64()? as f32,
                    ),
                })
            })
            .collect();
        if !parsed.is_empty() {
            map.insert(key.clone(), parsed);
        }
    }
    ScreenCatalog(map)
}

// --- assets / entities ---------------------------------------------------------

/// One quad child per catalog quad; `kit` feeds the shell's hostname flavor.
#[derive(Component)]
struct TerminalScreen {
    kit: String,
}

#[derive(Resource)]
struct TerminalAssets {
    mesh: Handle<Mesh>,
    idle_mat: Handle<StandardMaterial>,
    live_mat: Handle<StandardMaterial>,
}

#[derive(Component)]
struct TerminalPrompt;
#[derive(Component)]
struct TerminalText;
#[derive(Component)]
struct TerminalCamera;

/// Idle screens share one procedural texture: dark green glow + scanlines +
/// a bright cursor block top-left, so unfocused monitors read as "on".
fn idle_image() -> Image {
    const W: usize = 128;
    const H: usize = 80;
    let mut data = vec![0u8; W * H * 4];
    for y in 0..H {
        for x in 0..W {
            let mut v: u8 = if y % 3 == 0 { 12 } else { 26 };
            // faint vignette
            if x < 4 || x >= W - 4 || y < 3 || y >= H - 3 {
                v /= 2;
            }
            // cursor block, one line into the "screen"
            if (6..14).contains(&x) && (8..12).contains(&y) {
                v = 150;
            }
            let i = (y * W + x) * 4;
            data[i] = v / 3;
            data[i + 1] = v;
            data[i + 2] = v / 2;
            data[i + 3] = 255;
        }
    }
    Image::new(
        Extent3d { width: W as u32, height: H as u32, depth_or_array_layers: 1 },
        TextureDimension::D2,
        data,
        TextureFormat::Rgba8UnormSrgb,
        RenderAssetUsages::default(),
    )
}

fn setup_terminal_assets(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
    mut images: ResMut<Assets<Image>>,
) {
    let idle_img = images.add(idle_image());
    let mut live = Image::new_fill(
        Extent3d { width: LIVE_W, height: LIVE_H, depth_or_array_layers: 1 },
        TextureDimension::D2,
        &[0, 0, 0, 255],
        TextureFormat::Rgba8UnormSrgb,
        RenderAssetUsages::default(),
    );
    live.texture_descriptor.usage = TextureUsages::TEXTURE_BINDING
        | TextureUsages::COPY_DST
        | TextureUsages::RENDER_ATTACHMENT;
    let live_img = images.add(live);

    let screen_mat = |emissive: LinearRgba, tex: Handle<Image>| StandardMaterial {
        base_color: Color::BLACK,
        emissive,
        emissive_texture: Some(tex),
        reflectance: 0.02,
        perceptual_roughness: 1.0,
        ..default()
    };
    let assets = TerminalAssets {
        mesh: meshes.add(Rectangle::new(1.0, 1.0)),
        // idle texture is pre-tinted green; boost it uniformly
        idle_mat: materials.add(screen_mat(LinearRgba::rgb(2.2, 2.2, 2.2), idle_img)),
        // live text is green already; keep emissive neutral-bright
        live_mat: materials.add(screen_mat(LinearRgba::rgb(1.8, 1.8, 1.8), live_img.clone())),
    };
    commands.insert_resource(assets);

    // Offscreen shell renderer: sleeping Camera2d → live texture.
    commands.spawn((
        TerminalCamera,
        Camera2d,
        Camera {
            clear_color: ClearColorConfig::Custom(Color::BLACK),
            order: -1,
            is_active: false,
            ..default()
        },
        RenderTarget::Image(ImageRenderTarget::from(live_img)),
        RenderLayers::layer(TERMINAL_LAYER),
    ));
    commands.spawn((
        TerminalText,
        Text2d::new(String::new()),
        TextFont { font_size: 15.0, ..default() },
        TextColor(Color::srgb(0.62, 1.0, 0.72)),
        Anchor::TOP_LEFT,
        Transform::from_xyz(-(LIVE_W as f32) / 2.0 + 10.0, LIVE_H as f32 / 2.0 - 6.0, 0.0),
        RenderLayers::layer(TERMINAL_LAYER),
    ));
}

fn spawn_prompt(mut commands: Commands) {
    commands.spawn((
        TerminalPrompt,
        Node {
            position_type: PositionType::Absolute,
            width: Val::Percent(100.0),
            bottom: Val::Px(150.0),
            justify_content: JustifyContent::Center,
            ..default()
        },
        Visibility::Hidden,
        GlobalZIndex(40),
        children![(
            Text::new("[E]  terminal"),
            TextFont { font_size: 14.0, ..default() },
            TextColor(theme::ACCENT),
        )],
    ));
}

/// Glue a screen quad onto every newly placed prop the catalog knows.
/// Covers editor authoring, editor playtest, and real runs alike — anything
/// spawning a `KenneyModule` (even ghosts: the preview is a feature).
fn attach_screens(
    mut commands: Commands,
    catalog: Res<ScreenCatalog>,
    assets: Res<TerminalAssets>,
    pieces: Query<(Entity, &KenneyModule), Added<KenneyModule>>,
) {
    for (entity, module) in &pieces {
        let key = format!("{}/{}", module.kit.unwrap_or("space"), module.name);
        let Some(quads) = catalog.0.get(&key) else {
            continue;
        };
        let kit = module.kit.unwrap_or("space").to_string();
        for q in quads {
            let right = q.up.cross(q.normal).normalize();
            let rot = Quat::from_mat3(&Mat3::from_cols(right, q.up, q.normal));
            let child = commands
                .spawn((
                    Mesh3d(assets.mesh.clone()),
                    MeshMaterial3d(assets.idle_mat.clone()),
                    Transform::from_translation(q.center + q.normal * 0.003)
                        .with_rotation(rot)
                        .with_scale(Vec3::new(q.size.x, q.size.y, 1.0)),
                    TerminalScreen { kit: kit.clone() },
                    NotShadowCaster,
                ))
                .id();
            commands.entity(entity).add_child(child);
        }
    }
}

// --- focus / interaction --------------------------------------------------------

struct ActiveSession {
    screen: Entity,
    shell: Shell,
    dirty: bool,
}

#[derive(Resource, Default)]
struct TerminalFocus {
    session: Option<ActiveSession>,
    /// 0 = player view, 1 = fully on the screen. Eased both directions.
    blend: f32,
}

fn close_session(
    focus: &mut TerminalFocus,
    capture: &mut InputCapture,
    commands: &mut Commands,
    assets: &TerminalAssets,
    cams: &mut Query<&mut Camera, With<TerminalCamera>>,
) {
    if let Some(s) = focus.session.take() {
        // The piece (and quad) may already be despawned on map switches.
        if let Ok(mut e) = commands.get_entity(s.screen) {
            e.try_insert(MeshMaterial3d(assets.idle_mat.clone()));
        }
    }
    capture.0 = false;
    if let Ok(mut cam) = cams.single_mut() {
        cam.is_active = false;
    }
}

/// Show "[E] terminal" for the best screen in reach; open a session on E.
/// NPCs win: if an NPC is in talk range and faced, the terminal stays quiet
/// (the server would otherwise open the dialogue on the same keypress).
fn prompt_and_open(
    mut keys: ResMut<ButtonInput<KeyCode>>,
    mut capture: ResMut<InputCapture>,
    mut focus: ResMut<TerminalFocus>,
    assets: Res<TerminalAssets>,
    mut commands: Commands,
    screens: Query<(Entity, &GlobalTransform, &TerminalScreen)>,
    npcs: Query<&Transform, With<Npc>>,
    player: Query<(&Transform, Option<&PlayerAlive>), With<OwnPlayer>>,
    camera: Query<&Transform, (With<FlyCamera>, Without<OwnPlayer>)>,
    mut prompt: Query<&mut Visibility, With<TerminalPrompt>>,
    mut cams: Query<&mut Camera, With<TerminalCamera>>,
    mut text: Query<&mut Text2d, With<TerminalText>>,
) {
    let Ok(mut vis) = prompt.single_mut() else {
        return;
    };
    let hide = |vis: &mut Visibility| *vis = Visibility::Hidden;
    if capture.0 || focus.session.is_some() {
        hide(&mut vis);
        return;
    }
    let Ok((ptf, alive)) = player.single() else {
        hide(&mut vis);
        return;
    };
    if alive.is_some_and(|a| !a.0) {
        hide(&mut vis);
        return;
    }
    let Ok(cam_tf) = camera.single() else {
        hide(&mut vis);
        return;
    };
    let fwd = *cam_tf.forward();

    // Dialogue has priority on E (mirrors dialogue::sync_talk_prompt).
    let npc_in_reach = npcs.iter().any(|npc| {
        let to = npc.translation - ptf.translation;
        to.length() < 3.2 && to.normalize_or_zero().dot(fwd) > 0.92
    });
    if npc_in_reach {
        hide(&mut vis);
        return;
    }

    let mut best: Option<(Entity, &TerminalScreen, f32, Vec3)> = None;
    for (entity, gtf, screen) in &screens {
        let (_, rot, pos) = gtf.to_scale_rotation_translation();
        let to = pos - ptf.translation;
        let dist = to.length();
        if dist > PROMPT_RANGE {
            continue;
        }
        // camera roughly pointed at it, and we're on its front side
        if to.normalize_or_zero().dot(fwd) < FACING_DOT {
            continue;
        }
        let normal = rot * Vec3::Z;
        if normal.dot(ptf.translation - pos) < 0.0 {
            continue;
        }
        if best.as_ref().is_none_or(|(_, _, d, _)| dist < *d) {
            best = Some((entity, screen, dist, pos));
        }
    }
    let Some((entity, screen, _, pos)) = best else {
        hide(&mut vis);
        return;
    };
    *vis = Visibility::Visible;

    if keys.just_pressed(KeyCode::KeyE) {
        // Eat the press: send_input must not ship it as an NPC interact.
        keys.clear_just_pressed(KeyCode::KeyE);
        let seed = (pos.x.abs() * 7.31 + pos.z.abs() * 3.17) as u32;
        let shell = Shell::new(&screen.kit, seed, SHELL_COLS, SHELL_ROWS);
        if let Ok(mut t) = text.single_mut() {
            t.0 = shell.screen_text();
        }
        commands
            .entity(entity)
            .insert(MeshMaterial3d(assets.live_mat.clone()));
        if let Ok(mut cam) = cams.single_mut() {
            cam.is_active = true;
        }
        focus.session = Some(ActiveSession { screen: entity, shell, dirty: false });
        capture.0 = true;
        *vis = Visibility::Hidden;
    }
}

/// While a session is open, clear the whole `ButtonInput<KeyCode>` state each
/// frame so no gameplay/editor hotkey (G playtest toggle, B dev rings, T
/// labels, Tab…) can fire — the keyboard is the computer's. Esc survives:
/// it's the "leave the terminal" key. `terminal_keys` itself reads raw
/// `KeyboardInput` messages, which this doesn't touch.
fn block_keys_during_session(
    focus: Res<TerminalFocus>,
    mut keys: ResMut<ButtonInput<KeyCode>>,
) {
    if focus.session.is_none() {
        return;
    }
    let esc_down = keys.pressed(KeyCode::Escape);
    let esc_just = keys.just_pressed(KeyCode::Escape);
    keys.reset_all();
    if esc_down {
        keys.press(KeyCode::Escape);
        if !esc_just {
            keys.clear_just_pressed(KeyCode::Escape);
        }
    }
}

/// Route raw keyboard input into the shell while a session is open.
fn terminal_keys(
    mut keyboard: MessageReader<KeyboardInput>,
    mut keys: ResMut<ButtonInput<KeyCode>>,
    mut capture: ResMut<InputCapture>,
    mut focus: ResMut<TerminalFocus>,
    assets: Res<TerminalAssets>,
    mut commands: Commands,
    mut cams: Query<&mut Camera, With<TerminalCamera>>,
    mut text: Query<&mut Text2d, With<TerminalText>>,
) {
    let focus = &mut *focus;
    let Some(session) = focus.session.as_mut() else {
        keyboard.clear();
        return;
    };
    if keys.just_pressed(KeyCode::Escape) {
        // Eat it so fly_camera's Esc handler doesn't ungrab the cursor.
        keys.clear_just_pressed(KeyCode::Escape);
        close_session(focus, &mut capture, &mut commands, &assets, &mut cams);
        return;
    }
    for ev in keyboard.read() {
        if ev.state != ButtonState::Pressed {
            continue;
        }
        match &ev.logical_key {
            Key::Character(s) => {
                for c in s.chars() {
                    session.shell.type_char(c);
                }
                session.dirty = true;
            }
            Key::Space => {
                session.shell.type_char(' ');
                session.dirty = true;
            }
            Key::Backspace => {
                session.shell.backspace();
                session.dirty = true;
            }
            Key::Enter => {
                session.shell.submit();
                session.dirty = true;
            }
            _ => {}
        }
    }
    if session.dirty {
        session.dirty = false;
        if let Ok(mut t) = text.single_mut() {
            t.0 = session.shell.screen_text();
        }
    }
}

/// Dying, getting shoved out of reach, or the screen despawning (map switch)
/// all disconnect the session.
fn auto_close(
    mut capture: ResMut<InputCapture>,
    mut focus: ResMut<TerminalFocus>,
    assets: Res<TerminalAssets>,
    mut commands: Commands,
    screens: Query<&GlobalTransform, With<TerminalScreen>>,
    player: Query<(&Transform, Option<&PlayerAlive>), With<OwnPlayer>>,
    mut cams: Query<&mut Camera, With<TerminalCamera>>,
) {
    let focus = &mut *focus;
    let Some(session) = focus.session.as_ref() else {
        return;
    };
    let screen_pos = screens.get(session.screen).ok().map(|g| g.translation());
    let close = match (screen_pos, player.single()) {
        (Some(pos), Ok((ptf, alive))) => {
            alive.is_some_and(|a| !a.0) || ptf.translation.distance(pos) > CLOSE_RANGE
        }
        _ => true,
    };
    if close {
        close_session(focus, &mut capture, &mut commands, &assets, &mut cams);
    }
}

/// Blend the camera onto the focused screen (and back out). Runs in
/// PostUpdate after every gameplay camera driver wrote its transform, so the
/// player-view transform is this frame's blend source.
fn focus_camera(
    time: Res<Time>,
    focus: Res<TerminalFocus>,
    screens: Query<&GlobalTransform, With<TerminalScreen>>,
    mut camera: Query<(&mut Transform, &Projection), With<FlyCamera>>,
    mut blend: Local<f32>,
) {
    let target_active = focus
        .session
        .as_ref()
        .and_then(|s| screens.get(s.screen).ok());
    let dir = if target_active.is_some() { 1.0 } else { -1.0 };
    *blend = (*blend + dir * time.delta_secs() * 3.0).clamp(0.0, 1.0);
    if *blend <= 0.0 {
        return;
    }
    let Ok((mut cam_tf, projection)) = camera.single_mut() else {
        return;
    };
    // While blending out the screen may be gone; hold the last pose source
    // (the gameplay camera) and just decay.
    let Some(gtf) = target_active else {
        return;
    };
    let (scale, rot, center) = gtf.to_scale_rotation_translation();
    let normal = rot * Vec3::Z;
    let screen_up = rot * Vec3::Y;
    let (w, h) = (scale.x, scale.y);

    let fov = match projection {
        Projection::Perspective(p) => p.fov,
        _ => std::f32::consts::FRAC_PI_4,
    };
    let half_tan = (fov * 0.5).tan();
    // Fit height, and width assuming ~16:9; pad so the bezel stays visible.
    let d_h = (h * 0.5) / half_tan * 1.30;
    let d_w = (w * 0.5) / (half_tan * 1.6) * 1.15;
    let dist = d_h.max(d_w).max(0.35);

    let up = if normal.y.abs() > 0.7 { screen_up } else { Vec3::Y };
    let target =
        Transform::from_translation(center + normal * dist).looking_at(center, up);

    let t = *blend * *blend * (3.0 - 2.0 * *blend); // smoothstep
    cam_tf.translation = cam_tf.translation.lerp(target.translation, t);
    cam_tf.rotation = cam_tf.rotation.slerp(target.rotation, t);
}
